//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPixelPenguinsWA.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", ConfigurationName="ServiceReference2.RolWS")]
    public interface RolWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/obtenerRolPorIdRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/obtenerRolPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdResponse obtenerRolPorId(SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/obtenerRolPorIdRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/obtenerRolPorIdResponse")]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdResponse> obtenerRolPorIdAsync(SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/listarTodosRolesRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/listarTodosRolesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesResponse listarTodosRoles(SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/listarTodosRolesRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/listarTodosRolesResponse")]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesResponse> listarTodosRolesAsync(SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/insertarRolRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/insertarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPixelPenguinsWA.ServiceReference2.insertarRolResponse insertarRol(SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/insertarRolRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/insertarRolResponse")]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.insertarRolResponse> insertarRolAsync(SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/modificarRolRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/modificarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPixelPenguinsWA.ServiceReference2.modificarRolResponse modificarRol(SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/modificarRolRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/modificarRolResponse")]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.modificarRolResponse> modificarRolAsync(SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/eliminarRolRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/eliminarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPixelPenguinsWA.ServiceReference2.eliminarRolResponse eliminarRol(SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/eliminarRolRequest", ReplyAction="http://services.usuario.pixelpenguins.pucp.edu.pe/RolWS/eliminarRolResponse")]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.eliminarRolResponse> eliminarRolAsync(SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idRolField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
                this.RaisePropertyChanged("idRol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerRolPorId", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerRolPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRol;
        
        public obtenerRolPorIdRequest() {
        }
        
        public obtenerRolPorIdRequest(int idRol) {
            this.idRol = idRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerRolPorIdResponse", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerRolPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPixelPenguinsWA.ServiceReference2.rol @return;
        
        public obtenerRolPorIdResponse() {
        }
        
        public obtenerRolPorIdResponse(SoftPixelPenguinsWA.ServiceReference2.rol @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRoles", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosRolesRequest {
        
        public listarTodosRolesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRolesResponse", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPixelPenguinsWA.ServiceReference2.rol[] @return;
        
        public listarTodosRolesResponse() {
        }
        
        public listarTodosRolesResponse(SoftPixelPenguinsWA.ServiceReference2.rol[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRol", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPixelPenguinsWA.ServiceReference2.rol rol;
        
        public insertarRolRequest() {
        }
        
        public insertarRolRequest(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRolResponse", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarRolResponse() {
        }
        
        public insertarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRol", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class modificarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPixelPenguinsWA.ServiceReference2.rol rol;
        
        public modificarRolRequest() {
        }
        
        public modificarRolRequest(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRolResponse", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class modificarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarRolResponse() {
        }
        
        public modificarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRol", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class eliminarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPixelPenguinsWA.ServiceReference2.rol rol;
        
        public eliminarRolRequest() {
        }
        
        public eliminarRolRequest(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRolResponse", WrapperNamespace="http://services.usuario.pixelpenguins.pucp.edu.pe", IsWrapped=true)]
    public partial class eliminarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.usuario.pixelpenguins.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarRolResponse() {
        }
        
        public eliminarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RolWSChannel : SoftPixelPenguinsWA.ServiceReference2.RolWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RolWSClient : System.ServiceModel.ClientBase<SoftPixelPenguinsWA.ServiceReference2.RolWS>, SoftPixelPenguinsWA.ServiceReference2.RolWS {
        
        public RolWSClient() {
        }
        
        public RolWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RolWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdResponse SoftPixelPenguinsWA.ServiceReference2.RolWS.obtenerRolPorId(SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest request) {
            return base.Channel.obtenerRolPorId(request);
        }
        
        public SoftPixelPenguinsWA.ServiceReference2.rol obtenerRolPorId(int idRol) {
            SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest();
            inValue.idRol = idRol;
            SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdResponse retVal = ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).obtenerRolPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdResponse> SoftPixelPenguinsWA.ServiceReference2.RolWS.obtenerRolPorIdAsync(SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest request) {
            return base.Channel.obtenerRolPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdResponse> obtenerRolPorIdAsync(int idRol) {
            SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.obtenerRolPorIdRequest();
            inValue.idRol = idRol;
            return ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).obtenerRolPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesResponse SoftPixelPenguinsWA.ServiceReference2.RolWS.listarTodosRoles(SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest request) {
            return base.Channel.listarTodosRoles(request);
        }
        
        public SoftPixelPenguinsWA.ServiceReference2.rol[] listarTodosRoles() {
            SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest();
            SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesResponse retVal = ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).listarTodosRoles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesResponse> SoftPixelPenguinsWA.ServiceReference2.RolWS.listarTodosRolesAsync(SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest request) {
            return base.Channel.listarTodosRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesResponse> listarTodosRolesAsync() {
            SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.listarTodosRolesRequest();
            return ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).listarTodosRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPixelPenguinsWA.ServiceReference2.insertarRolResponse SoftPixelPenguinsWA.ServiceReference2.RolWS.insertarRol(SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest request) {
            return base.Channel.insertarRol(request);
        }
        
        public int insertarRol(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest();
            inValue.rol = rol;
            SoftPixelPenguinsWA.ServiceReference2.insertarRolResponse retVal = ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).insertarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.insertarRolResponse> SoftPixelPenguinsWA.ServiceReference2.RolWS.insertarRolAsync(SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest request) {
            return base.Channel.insertarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.insertarRolResponse> insertarRolAsync(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.insertarRolRequest();
            inValue.rol = rol;
            return ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).insertarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPixelPenguinsWA.ServiceReference2.modificarRolResponse SoftPixelPenguinsWA.ServiceReference2.RolWS.modificarRol(SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest request) {
            return base.Channel.modificarRol(request);
        }
        
        public int modificarRol(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest();
            inValue.rol = rol;
            SoftPixelPenguinsWA.ServiceReference2.modificarRolResponse retVal = ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).modificarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.modificarRolResponse> SoftPixelPenguinsWA.ServiceReference2.RolWS.modificarRolAsync(SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest request) {
            return base.Channel.modificarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.modificarRolResponse> modificarRolAsync(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.modificarRolRequest();
            inValue.rol = rol;
            return ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).modificarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPixelPenguinsWA.ServiceReference2.eliminarRolResponse SoftPixelPenguinsWA.ServiceReference2.RolWS.eliminarRol(SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest request) {
            return base.Channel.eliminarRol(request);
        }
        
        public int eliminarRol(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest();
            inValue.rol = rol;
            SoftPixelPenguinsWA.ServiceReference2.eliminarRolResponse retVal = ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).eliminarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.eliminarRolResponse> SoftPixelPenguinsWA.ServiceReference2.RolWS.eliminarRolAsync(SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest request) {
            return base.Channel.eliminarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPixelPenguinsWA.ServiceReference2.eliminarRolResponse> eliminarRolAsync(SoftPixelPenguinsWA.ServiceReference2.rol rol) {
            SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest inValue = new SoftPixelPenguinsWA.ServiceReference2.eliminarRolRequest();
            inValue.rol = rol;
            return ((SoftPixelPenguinsWA.ServiceReference2.RolWS)(this)).eliminarRolAsync(inValue);
        }
    }
}
